version: "3.9"
services:
  app:
    build: .
    image: localhost/chat-app:latest
    container_name: chat_app
    command: ["python","-m","uvicorn", "main:app","--host","0.0.0.0","--port","8000"]
    env_file:
      - .env
    environment:
      DATABASE_URL: mysql+pymysql://root:root@db/chatDB
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: docker.io/library/mysql:8.0
    container_name: chat_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatDB
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
  

